var quat=quat||{};quat.solver=quat.solver||{};quat.solver.BackgroundLayer=cc.Layer.extend({ctor:function(){this._super();var a=new cc.LayerColor(cc.color(63,74,33,255));this.colorBackground=a;this.addChild(a);return!0}});quat=quat||{};quat.solver=quat.solver||{};
quat.solver.ChooseLetterLayer=cc.Layer.extend({ctor:function(a,b,c){this._super();this.fontSize=c;for(var e=c+20,d=Math.ceil(b/c)+1,g=[],h=0;h<d;h++){var f=new cc.LabelTTF("A","Arial",c);f.x=a/2;f.y=e/2+c+h*c;f.zIndex=1;this.addChild(f);g.push(f)}this.letterPool=g;d=new cc.LayerColor(cc.color(133,150,83,255));d.width=a;d.height=b;d.y=e/2+c/2;d.zIndex=0;this.colorBackground=d;this.addChild(d);this.uppercase="ABCDEFGHIJKLMNOPQRSTUVWXYZ";return!0},redrawFromLetter:function(a){var b=this.uppercase;a=
a.charCodeAt(0)-65;for(var c=0;c<this.letterPool.length;c++){var e=this.letterPool[c],d=(a-c)%b.length;0>d&&(d+=b.length);e.string=b[d]}},setBaseLetter:function(a){a=a.toUpperCase();this.redrawFromLetter(a);this.baseLetterIndex=a.charCodeAt(0)-65},getBaseLetter:function(){return this.letterPool[0].string},setOffset:function(a){a=this.baseLetterIndex+Math.floor(a/this.fontSize);a%=this.uppercase.length;0>a&&(a+=this.uppercase.length);this.redrawFromLetter(this.uppercase[a])}});quat=quat||{};quat.solver=quat.solver||{};quat.solver.KeyboardInputManager=function(a){this.quatGame=a.quatGame;this.solutionLayer=a.solutionLayer;this.chooseLetterLayer=a.chooseLetterLayer;this.sc=a.stateController;this.lastColumn=-1};
quat.solver.KeyboardInputManager.prototype.inputKeycode=function(a){var b=String.fromCharCode(a);if(isNaN(b)){var c=b.charCodeAt(0)-65;this.sc.state==this.sc.states.CHANGING_LETTER_NODRAG&&26>c&&0<=c?(a=this.quatGame.getCurrentWord(),b=a.substr(0,this.lastColumn)+b+a.substr(this.lastColumn+1),b=b.toLowerCase(),this.quatGame.addWord(b)?(this.quatGame.atGoal()&&(this.quatGame.newPuzzle(),this.solutionLayer.updateGoal(this.quatGame.getGoal())),this.solutionLayer.updateSolution(this.quatGame.getCurrentSteps())):
console.log(b+" is not a word"),this.sc.IDLE()):this.sc.state==this.sc.states.CHANGING_LETTER_NODRAG&&8==a?this.sc.IDLE():this.sc.state==this.sc.states.IDLE&&8==a&&(this.quatGame.goBack(),this.sc.IDLE())}else b=+b,1>b||4<b?this.sc.IDLE():(--b,this.lastColumn=b,this.sc.CHOOSING_LETTER(b),this.sc.CHANGING_LETTER_NODRAG())};quat=quat||{};quat.solver=quat.solver||{};
quat.solver.PuzzleScene=cc.Scene.extend({ctor:function(a,b){this._super();this.windowWidth=a;this.windowHeight=b;return!0},calculateSize:function(){var a=this.windowWidth,b=this.windowHeight,c=0,e=0;a>=b||a<b&&300<a?(c=Math.min(a,300),e=a/2-c/2):(c=a,e=0);return{width:c,height:b,x:e,y:0}},onEnter:function(){this._super();var a=new quat.GameInfo;this.quatGame=a;a.newPuzzle();var b=new quat.solver.BackgroundLayer,c=this.calculateSize(),e=.18*c.width,d=new quat.solver.SolutionLayer(c.width,c.height,
e),e=new quat.solver.ChooseLetterLayer(c.width/4,c.height,e);e.setBaseLetter("D");e.setVisible(!1);d.x=c.x;d.y=c.y;e.x=c.x;e.y=c.y;this.addChild(b);this.addChild(d);this.addChild(e);this.backgroundLayer=b;this.solutionLayer=d;this.chooseLetterLayer=e;this.solutionSize=c;d.updateSolution(a.getCurrentSteps());d.updateGoal(a.getGoal());this.stateController=new quat.solver.StateController(this);var g=new quat.solver.TouchInputManager(this);this.touchInputManager=g;var h=new quat.solver.KeyboardInputManager(this);
this.keyInputManager=h;var f=function(a){return{x:a.getLocationX()-c.x,y:a.getLocationY()-c.y}},k=!1;cc.eventManager.addListener({event:cc.EventListener.TOUCH_ONE_BY_ONE,swallowTouches:!0,onTouchBegan:function(a){if(k)return!1;k=!0;a=f(a);g.inputBegan(a.x,a.y);return!0},onTouchMoved:function(a){a=f(a);g.inputMoved(a.x,a.y);return!0},onTouchEnded:function(a){a=f(a);g.inputDone(a.x,a.y);k=!1;return!0}},this);cc.eventManager.addListener({event:cc.EventListener.KEYBOARD,onKeyReleased:function(a,b){h.inputKeycode(a)}},
this)}});quat=quat||{};quat.solver=quat.solver||{};
quat.solver.SolutionLayer=cc.Layer.extend({ctor:function(a,b,c){this._super();a={width:a,height:b};b=a.width/4;this.size=a;this.fontSize=c=.18*a.width;var e=c+20;this.fontTotal=e;for(var d=Math.ceil(a.height/e)+1,g=[],h=0;h<d;h++){var f=new quat.solver.WordNode(c,b);f.setVisible(!1);f.x=b/2;this.addChild(f);g.push(f)}this.wordPool=g;d=new quat.solver.WordNode(c,b);c=e/2+c/2;d.x=b/2;d.y=c/2;d.zIndex=1;d.setColor(cc.color(62,33,74,255));this.addChild(d);this.goalWord=d;b=new cc.LayerColor(cc.color(125,
150,53,255));b.height=c;b.width=a.width;b.zIndex=0;this.goalBackground=b;this.addChild(b);return!0},setCurrentOpacity:function(a){this.wordPool[0].setOpacity(a)},pointInCurrentWord:function(a,b){var c=this.fontTotal/2+this.fontSize/2,e=c+this.fontSize;if(a>this.size.width||b>e||0>a||b<c)return!1;c=this.size.width/4;return(a-a%c)/c},pointInColumn:function(a,b){var c=this.fontTotal/2+this.fontSize/2;if(0>a||a>this.size.width||b<c)return!1;c=this.size.width/4;return(a-a%c)/c},bottomOfCurrentWord:function(){return this.fontTotal/
2+this.fontSize/2},topOfCurrentWord:function(){return this.bottomOfCurrentWord()+this.fontSize},updateSolution:function(a){if(!(1>a.length)){a=a.slice().reverse();for(var b=0;b<this.wordPool.length;b++){var c=this.wordPool[b];c.setVisible(!1)}for(b=0;b<Math.min(a.length,this.wordPool.length);b++)c=this.wordPool[b],c.y=this.fontTotal/2+this.fontSize+b*this.fontSize,c.changeWord(a[b]),c.setVisible(!0)}},updateGoal:function(a){this.goalWord.changeWord(a)}});quat=quat||{};quat.solver=quat.solver||{};quat.solver.StateController=function(a){this.quatGame=a.quatGame;this.backgroundLayer=a.backgroundLayer;this.solutionLayer=a.solutionLayer;this.chooseLetterLayer=a.chooseLetterLayer;this.solutionSize=a.solutionSize;this.states={IDLE:0,CHOOSING_LETTER:1,CHANGING_LETTER_DRAG:2,CHANGING_LETTER_NODRAG:3,GESTURING:4,ERASING_WORD:5};this.state=this.states.IDLE;this.previousOffset=0};
quat.solver.StateController.prototype.IDLE=function(){this.state!=this.states.CHANGING_LETTER_NODRAG&&this.state!=this.states.CHOOSING_LETTER||this.chooseLetterLayer.setVisible(!1);this.solutionLayer.updateSolution(this.quatGame.getCurrentSteps());this.state=this.states.IDLE};
quat.solver.StateController.prototype.CHOOSING_LETTER=function(a){this.chooseLetterLayer.x=this.solutionSize.width/4*a+this.solutionSize.x;this.chooseLetterLayer.setBaseLetter(this.quatGame.getCurrentWord()[a]);this.chooseLetterLayer.setVisible(!0);this.state=this.states.CHOOSING_LETTER};quat.solver.StateController.prototype.CHANGING_LETTER_DRAG=function(){this.state=this.states.CHANGING_LETTER_DRAG};quat.solver.StateController.prototype.CHANGING_LETTER_NODRAG=function(){this.state=this.states.CHANGING_LETTER_NODRAG};
quat.solver.StateController.prototype.GESTURING=function(){this.state=this.states.GESTURING};quat.solver.StateController.prototype.ERASING_WORD=function(){this.state=this.states.ERASING_WORD};quat=quat||{};quat.solver=quat.solver||{};quat.solver.TouchInputManager=function(a){this.quatGame=a.quatGame;this.solutionLayer=a.solutionLayer;this.solutionSize=a.solutionSize;this.chooseLetterLayer=a.chooseLetterLayer;this.sc=a.stateController;this.lastColumn=-1;this.lastMouseDown={};this.previousOffset=0};
quat.solver.TouchInputManager.prototype.inputBegan=function(a,b){this.lastMouseDown={x:a,y:b};if(this.sc.state==this.sc.states.IDLE){var c=this.solutionLayer.pointInCurrentWord(a,b);!1!==c?(this.lastColumn=c,this.sc.CHOOSING_LETTER(c)):b>this.solutionLayer.topOfCurrentWord()&&this.sc.GESTURING()}else this.sc.state==this.sc.states.CHANGING_LETTER_NODRAG&&(c=this.solutionLayer.pointInColumn(a,b),!1===c||c!=this.lastColumn?this.sc.IDLE():this.sc.CHANGING_LETTER_DRAG())};
quat.solver.TouchInputManager.prototype.inputMoved=function(a,b){if(this.sc.state==this.sc.states.CHOOSING_LETTER){var c=this.solutionLayer.pointInCurrentWord(a,b);!1===c?this.solutionLayer.pointInColumn(a,b)==this.lastColumn?(this.sc.CHANGING_LETTER_DRAG(),c=b-this.lastMouseDown.y,this.chooseLetterLayer.setOffset(c)):this.sc.IDLE():(this.sc.CHOOSING_LETTER(c),this.lastColumn=c)}else this.sc.state==this.sc.states.CHANGING_LETTER_DRAG&&(c=b-this.lastMouseDown.y,this.chooseLetterLayer.setOffset(c))};
quat.solver.TouchInputManager.prototype.finishWord=function(){this.sc.state=this.sc.states.IDLE;this.chooseLetterLayer.setVisible(!1);var a=this.quatGame.getCurrentWord(),a=a.substr(0,this.lastColumn)+this.chooseLetterLayer.getBaseLetter()+a.substr(this.lastColumn+1),a=a.toLowerCase();this.quatGame.addWord(a)?(this.quatGame.atGoal()&&(this.quatGame.newPuzzle(),this.solutionLayer.updateGoal(this.quatGame.getGoal())),this.solutionLayer.updateSolution(this.quatGame.getCurrentSteps())):console.log(a+
" is not a word")};
quat.solver.TouchInputManager.prototype.inputDone=function(a,b){if(this.sc.state==this.sc.states.CHOOSING_LETTER)this.sc.IDLE();else if(this.sc.state==this.sc.states.CHANGING_LETTER_DRAG){var c=this.solutionLayer.pointInCurrentWord(a,b),e=this.solutionLayer.pointInColumn(a,b);!1===c&&!1!==e?(this.chooseLetterLayer.setBaseLetter(this.chooseLetterLayer.getBaseLetter()),this.sc.CHANGING_LETTER_NODRAG()):c===this.lastColumn&&e==this.lastColumn?this.finishWord():this.sc.CHANGING_LETTER_NODRAG()}else this.sc.state==this.sc.states.CHANGING_LETTER_NODRAG?
this.finishWord():this.sc.state==this.sc.states.GESTURING?this.sc.IDLE():this.sc.state==this.sc.states.ERASING_WORD&&(this.quatGame.goBack(),this.sc.IDLE())};quat=quat||{};quat.solver=quat.solver||{};quat.solver.WordNode=cc.Node.extend({ctor:function(a,b){this._super();this.fontSize=a;this.fontGap=b;for(var c=[],e=0;4>e;e++){var d=new cc.LabelTTF("A","Arial",a);d.x=e*this.fontGap;d.y=0;this.addChild(d);c.push(d)}this.rowPool=c;return!0},changeWord:function(a){for(var b=0;4>b;b++)this.rowPool[b].string=a[b].toUpperCase()},setColor:function(a){for(var b=0;4>b;b++)this.rowPool[b].setFontFillColor(a)},setOpacity:function(a){for(var b=0;4>b;b++)this.rowPool[b].setOpacity(a)}});
